### PR TITLE
Add my team listing

### PR DESCRIPTION
**Pull request by burritosoftware**
Nice.

### CODE REVIEW

**Review by oscie57 — COMMENTED** [review]
burrito doesnt actually exist, so this is invalid...?

**Comment by burritosoftware** [comment]
> burrito doesnt actually exist, so this is invalid...?

it depends on the screen resolution/window size for some reason

**Comment by oscie57** [comment]
> > burrito doesnt actually exist, so this is invalid...?
> 
> ....
uh what happened, i got a reply from a person with no name and no pfp, with just "...."
like i said burrito doesnt exist so idk why this was submitted

**Comment by burritosoftware** [comment]
a lot of people are cut off and it depends on the size of the website, on my ultrawide i see myself fine

**Pull request merged**
